Repository stolostron/search-collector, pull requests merged in 2021-04, with the labels that each got.

#118 Delete duplicated Dockerfile.prow
  Dockerfile.prow
Labels: approved

#119 update deislabs/oras to latest version
  go.mod
  go.sum
Labels: approved, lgtm

#120 migrated to v1alpha2
  pkg/transforms/policyreport.go
  test-data/policyreport.json
Labels: approved, lgtm

#121 Add policy report result field to redis
  pkg/transforms/policyreport.go
  pkg/transforms/policyreport_test.go
  test-data/policyreport.json
Labels: approved, lgtm

#124 Add Argo app status to search collector
  pkg/transforms/argoapplication.go
  pkg/transforms/argoapplication_test.go
  test-data/argoapplication.json
Labels: approved, do-not-merge/hold, lgtm

#125 Update OWNERS and base docker image
  COMPONENT_VERSION
  Dockerfile
  OWNERS
  pkg/config/config.go
Labels: approved, lgtm

#126 loop through and get all policies in the report
  pkg/transforms/policyreport.go
  pkg/transforms/policyreport_test.go
  test-data/policyreport.json
Labels: approved, lgtm
