Repository stolostron/search-collector, pull requests merged in 2021-03, with the labels that each got.

#30 PolicyReport transformer
  pkg/reconciler/reconciler_test.go
  pkg/transforms/policyreport.go
  pkg/transforms/policyreport_test.go
  pkg/transforms/transformer.go
  test-data/policyreport.json
Labels: approved

#105 Update contact information
  build/Configfile
Labels: approved, lgtm

#106 Fix release-ff
  .travis.yml
Labels: approved, lgtm

#108 Prepare for prow - add unit-tests to Makefile.prow
  Makefile.prow
Labels: approved

#111 update golang.org/x/text version
  go.mod
  go.sum
Labels: approved, lgtm

#110 Add CONTRIBUTING.md
  CONTRIBUTING.md
  Makefile
Labels: approved, lgtm, ok-to-test

#112 [release 2.2] update golang.org/x/text version
  go.mod
  go.sum
Labels: lgtm

#116 remove deprecated selfLink
  pkg/reconciler/reconciler_test.go
  pkg/transforms/common.go
  pkg/transforms/common_test.go
  pkg/transforms/genericresource.go
Labels: approved, lgtm

#117 update apiVersion of test data
  test-data/daemonset.json
  test-data/deployment.json
  test-data/replicaset.json
Labels: approved, do-not-merge/hold, lgtm
