Repository stolostron/search-collector, pull requests merged in 2021-06, with the labels that each got.

#133 Add pr severity
  pkg/transforms/policyreport.go
  pkg/transforms/policyreport_test.go
Labels: approved, do-not-merge/hold, lgtm

#134 [release-2.1] Build selfLink when not present
  go.mod
  go.sum
  pkg/transforms/transformer.go
  pkg/transforms/transformer_test.go
Labels: lgtm

#135 Change field names for policyreport
  pkg/transforms/policyreport.go
  pkg/transforms/policyreport_test.go
Labels: approved, do-not-merge/hold

#129 Add contribution instructions to search-collector README.
  readme.md
Labels: approved

#136 rebuild https client when hub config secret expires
  pkg/config/config.go
  pkg/lease/lease.go
  pkg/send/sender.go
Labels: approved, lgtm

#137 Default Argo targetRevision to HEAD
  pkg/transforms/argoapplication.go
Labels: approved, lgtm
