Repository stolostron/search-collector, pull requests merged in 2022-07, with the labels that each got.

#204 Imagescan Rebuild: 2022-07-05
  readme.md
Labels: lgtm, dco-signoff: yes

#205 [release-2.6] Updated component version
  COMPONENT_VERSION
Labels: lgtm, dco-signoff: yes

#206 [release-2.5] Updated component version
  COMPONENT_VERSION
Labels: lgtm, dco-signoff: yes

#209 Update to go 1.18
  Dockerfile
  Makefile
  Makefile.prow
  build/.golangci.yml
  build/run-lint-check.sh
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#210 update lint script
  build/run-lint-check.sh
Labels: lgtm, approved, dco-signoff: yes

#212 added kind plural to properties
  pkg/transforms/transformer.go
  pkg/transforms/transformer_test.go
Labels: lgtm, approved, do-not-merge/hold, dco-signoff: yes

#207 [release-2.5] Updated OWNERS file approvers
  OWNERS
Labels: lgtm, approved, dco-signoff: yes

#208 [release-2.4] Updated OWNERS file approvers
  OWNERS
Labels: lgtm, approved, dco-signoff: yes
